### ISSUE TITLE
Packaging for conda-forge?

### ISSUE THREAD

**Issue by bollwyvl** [jpmorganchase/ipyregulartable#23]
Hi folks! Congrats on the release!

I'd :heart:  to package this for conda-forge, and am noticing a few _irregular_ things in the metadata/build:
- [ensure_python](https://github.com/jpmorganchase/ipyregulartable/blob/main/setup.py#L17) says `(('2.7', '>=3.7'))` but the trove classifiers claim `3.6`
  - which is right? or is *.7 only required for the build?
    - proposal: use [`python_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) which most `pip`s will actually honor
- the source tarballs doesn't include the `js/lib`
  - yeah, i know it says "source" on the tin, but i don't think it's generally expected that a `pip install` needs `node` (much less `yarn`) at install time, when error messages can get _very_ buried
    - proposal: include the built js in the sdist

Happy to PR some of these things!

**Comment by bollwyvl** [comment]
`conda-forge` builds are [up](https://anaconda.org/conda-forge/ipyregulartable/files)!

**Comment by timkpaine** [comment]
No need to package lib as both notebook and lab extension are packaged. Any changes in this regard should be done on the ipywidgets extension cookiecutter. Same for [ensure_python](https://github.com/jupyter-widgets/widget-ts-cookiecutter/blob/master/%7B%7Bcookiecutter.github_project_name%7D%7D/setup.py#L25), but I will drop 3.6 in a PR.

**Comment by timkpaine** [comment]
https://github.com/jpmorganchase/ipyregulartable/pull/25
